In [1]:
import pandas as pd

df = pd.read_csv("diabetes.csv")

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [12]:
X = df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin','BMI', 'DiabetesPedigreeFunction', 'Age']]
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [15]:
y = df['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [16]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [17]:
model.fit(X, y)

C:\Users\Hoai\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [23]:
import numpy as np
X = np.array(X)

In [24]:
X[0]

array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
        50.   ])

In [25]:
y1=model.predict([X[0]])

C:\Users\Hoai\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [29]:
y1 = model.predict(X)

C:\Users\Hoai\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [30]:
from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(y, y1)

0.7825520833333334

In [33]:
model.coef_ # w1, w2, w3, w4, w5, w6, w7, w8 -> hệ số nào lớn nhất thì thuộc tính đó ảnh hưởng nhiều đến kết quả 

array([[ 1.17252334e-01,  3.35998902e-02, -1.40873643e-02,
        -1.27046311e-03, -1.24032420e-03,  7.72022872e-02,
         1.41904184e+00,  1.00353200e-02]])

In [35]:
model.intercept_

array([-7.70291766])

In [42]:
w0= model.intercept_[0]
w1 =model.coef_[0,0]
w2 = model.coef_[0,1]
w3 = model.coef_[0,2]
w4 = model.coef_[0,3]
w5 = model.coef_[0,4]
w6 = model.coef_[0,5]
w7 = model.coef_[0,6]
w8 = model.coef_[0,7]
print(w0,w1,w2,w3,w4,w5,w6,w7,w8)
# Phương trình đường thẳng
yy= -(w0+w1*X[:,0]+w2*X[:,1]+w3*X[:,2]+w4*X[:,3]+w5*X[:,4]+w6*X[:,5]+w7*X[:,6])/w8


-7.702917661413902 0.11725233392821452 0.03359989023437728 -0.01408736434071672 -0.0012704631099890503 -0.0012403242035598642 0.07720228716662413 1.4190418381555894 0.010035320017430563
